### PR TITLE
Promise: implement and integrate GetPromiseResolve

### PR DESCRIPTION
**Pull request by rwaldron**
Refs:

- https://tc39.es/ecma262/#sec-getpromiseresolve
- https://tc39.es/ecma262/#_ref_9258
- https://tc39.es/ecma262/#_ref_9297
- https://tc39.es/ecma262/#_ref_9342

### CODE REVIEW

**Comment by devsnek** [comment]
So... I've already added this change to the `parser` branch, where development is happening right now. I'm not against merging this but I am fairly sure the build will still fail because `master` is horribly out of date, and there won't be a release.

**Comment by rwaldron** [comment]
How safe/reliable is it to use the `parser` branch?

**Comment by devsnek** [comment]
@rwaldron still failing like 20k tests, mostly due to not parsing assignment patterns correctly yet.

**Comment by rwaldron** [comment]
I think I can just run the code coverage report from this branch for now.

**Pull request merged**
