### PR TITLE
feat: support debugger

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by devsnek** [comment]
you can provide this yourself when you embed engine262

**Comment by Jack-Works** [comment]
It's not convenient to use the online version of engine262 when I want to pause the engine at a specific point.

**Comment by devsnek** [comment]
You should PR to the website then :)

**Comment by Jack-Works** [comment]
Oh, wait... This is not the website code? 🤣

**Comment by devsnek** [comment]
nah that's the engine262.github.io repo

**Comment by Jack-Works** [comment]
thanks, I'll do that later

**Pull request closed without merging**
